// <auto-generated />
using System;
using MATC84.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MATC84.Persistence.Migrations
{
    [DbContext(typeof(MATC84Context))]
    [Migration("20210926173847_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("MATC84.Domain.Model.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Semestre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeminarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PessoaId");

                    b.HasAlternateKey("Matricula");

                    b.HasIndex("SeminarioId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("MATC84.Domain.Model.Seminario", b =>
                {
                    b.Property<int>("SeminarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Nota")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QtdPessoas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeminarioId");

                    b.ToTable("Seminario");
                });

            modelBuilder.Entity("MATC84.Domain.Model.Pessoa", b =>
                {
                    b.HasOne("MATC84.Domain.Model.Seminario", "Seminario")
                        .WithMany("Grupo")
                        .HasForeignKey("SeminarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seminario");
                });

            modelBuilder.Entity("MATC84.Domain.Model.Seminario", b =>
                {
                    b.Navigation("Grupo");
                });
#pragma warning restore 612, 618
        }
    }
}
